"use client";
import {useState} from "react";
import Link from "next/link";
import Navbar from "@/components/Navbar";
type A={id:string;name:string;description:string;rank:"Bronze"|"Prata"|"Ouro";exophase:"sim"|"nao"|"nao_verificado";journey:boolean};
type R={game:{name:string;source:string};achievements:A[];warnings?:string[]};
export default function Page(){
 const [title,setTitle]=useState(""),[result,setResult]=useState<R|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function search(){if(!title.trim()){setError("Digite o nome do jogo.");return}setLoading(true);setError("");setResult(null);try{const r=await fetch("/api/admin/achievement-prep?title="+encodeURIComponent(title),{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.error||"Erro na busca.");setResult(p)}catch(e){setError(e instanceof Error?e.message:"Erro na busca.")}finally{setLoading(false)}}
 function toggle(id:string){setResult(r=>r?{...r,achievements:r.achievements.map(a=>a.id===id?{...a,journey:!a.journey}:a)}:r)}
 return <main className="min-h-screen bg-[#050505] text-white"><Navbar/><div className="mx-auto max-w-[1500px] px-5 py-8 lg:px-8">
 <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.28em] text-red-500">Admin • Preparador</p><h1 className="mt-2 text-4xl font-black">Preparar novo jogo</h1><p className="mt-2 text-sm text-white/40">Informe o jogo e carregue automaticamente suas conquistas para preparação.</p></div><Link href="/admin/jogos" className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-xs font-black uppercase text-white/55">Voltar para Jogos</Link></div>
 <section className="mt-7 rounded-[20px] border border-white/[.08] bg-[#090909] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-white/25">01</p><h2 className="mt-1 text-xl font-black">Nome do jogo</h2><div className="mt-5 flex flex-col gap-3 md:flex-row"><input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void search()} placeholder="Ex.: Black Myth: Wukong" className="flex-1 rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm font-bold outline-none placeholder:text-white/20"/><button onClick={()=>void search()} disabled={loading} className="rounded-xl border border-red-500/30 bg-red-500/10 px-6 py-3 text-xs font-black uppercase text-red-100 disabled:opacity-50">{loading?"Buscando...":"Buscar conquistas"}</button></div>{error&&<p className="mt-3 rounded-xl border border-red-500/20 bg-red-500/[.06] p-3 text-xs font-bold text-red-200">{error}</p>}</section>
 {result&&<><section className="mt-5 rounded-[20px] border border-white/[.08] bg-[#090909] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-red-500">02 • Resultado</p><div className="mt-1 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-black">{result.game.name}</h2><p className="text-xs text-white/30">{result.achievements.length} conquistas encontradas • Fonte: {result.game.source}</p></div><div className="rounded-2xl border border-red-500/20 bg-red-500/[.05] px-4 py-3 text-right"><p className="text-[8px] uppercase text-white/30">Jornada de Estreia</p><p className="text-lg font-black text-red-100">{result.achievements.filter(a=>a.journey).length} selecionadas</p></div></div>{result.warnings?.map(w=><p key={w} className="mt-3 text-xs text-yellow-100/60">• {w}</p>)}</section>
 <section className="mt-5 rounded-[20px] border border-white/[.08] bg-[#090909] p-5"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.18em] text-white/25">03</p><h2 className="text-xl font-black">Conquistas encontradas</h2></div><span className="text-[9px] uppercase text-white/30">Clique para Jornada</span></div><div className="mt-4 space-y-2">{result.achievements.map((a,i)=><button key={a.id} onClick={()=>toggle(a.id)} className={a.journey?"w-full rounded-2xl border border-red-500/30 bg-red-500/[.06] p-4 text-left":"w-full rounded-2xl border border-white/[.07] bg-black/20 p-4 text-left"}><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[8px] uppercase text-white/25">Conquista {i+1}</p><h3 className="mt-1 text-sm font-black">{a.name}</h3><p className="mt-2 text-xs text-white/35">{a.description||"Sem descrição disponível."}</p></div><div className="flex shrink-0 flex-wrap gap-2"><span className="rounded-full border border-white/10 px-3 py-1.5 text-[8px] font-black">{a.rank}</span><span className="rounded-full border border-violet-400/20 px-3 py-1.5 text-[8px] font-black text-violet-200/70">{a.exophase==="sim"?"Exophase":a.exophase==="nao"?"Sem Exophase":"Não verificado"}</span><span className="rounded-full border border-white/10 px-3 py-1.5 text-[8px] font-black">{a.journey?"Jornada":"Fora da Jornada"}</span></div></div></button>)}</div></section></>}
 </div></main>
}